language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - setup=basic
    - coverage=false
    - illuminate=default

sudo: false

branches:
  except:
    - gh-pages
    - /analysis-.*/

before_install:
  - if [[ $coverage = 'false' ]]; then phpenv config-rm xdebug.ini || true; fi

install:
  - if [[ $setup = 'basic'  ]] && [[ $illuminate = 'default'  ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-lowest; fi
  - if [[ $illuminate != 'default' ]]; then travis_retry composer require --dev --update-with-dependencies --prefer-dist --no-interaction --no-suggest illuminate/support "$illuminate"; fi
  - composer info | grep -e illuminate/support -e phpunit/phpunit -e phpstan/phpstan

script:
  - if [[ $coverage = 'true' ]]; then composer test-cover; else composer test; fi

after_success:
  - if [[ $coverage = 'true' ]]; then bash <(curl -s https://codecov.io/bash); fi

matrix:
  include:
    - php: 7.1.3
    - php: 7.1.3
      env: setup=lowest

    - php: 7.2
      env: coverage=true
    - php: 7.2
      env: setup=lowest
    - php: 7.2
      env: setup=stable
    - php: 7.2
      env: illuminate=6.*

    - php: 7.3
    - php: 7.3
      env: setup=lowest
    - php: 7.3
      env: illuminate=6.*

    - php: nightly


deploy:
  - provider: npm # <https://docs.travis-ci.com/user/deployment/npm/>
    email: $NPM_DEPLOY_EMAIL
    api_key: $NPM_DEPLOY_TOKEN
    on:
      tags: true
      branch: master
